version: '2'
services:

  kapiweb:
    image: registry.kapook.com/nethispeed/testapi/proxy_kapi
    networks:
      kpnetwork:
        ipv4_address: 192.168.1.34
    ports:
      - "80:80"

  kapifpm:
    image: registry.kapook.com/nethispeed/testapi/fpm_kapi
    networks:
      kpnetwork:
        ipv4_address: 192.168.1.55

  mysql13:
    image: registry.kapook.com/nethispeed/testapi/serv_mysqld
    networks:
      kpnetwork:
        ipv4_address: 192.168.1.146

  redis77:
    image: registry.kapook.com/nethispeed/testapi/serv_redis
    networks:
      kpnetwork:
        ipv4_address: 192.168.1.77

#  mongo167:
#    image: registry.kapook.com/nethispeed/testapi/serv_mongod
#    networks:
#      kpnetwork:
#        ipv4_address: 192.168.1.101

  couchbase121:
    image: registry.kapook.com/nethispeed/testapi/serv_couchbase 
    networks:
      kpnetwork:
        ipv4_address: 192.168.1.121

networks:
  kpnetwork:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24

