version: '2'
services:

  proxy:
    image: nethispeed/alpine-resty:latest
    volumes:
      - /data/www:/var/www/html
    networks:
      network:
        ipv4_address: 192.168.101.2
    ports:
      - "80:80"

  phpfpm:
    image: nethispeed/alpine-phpfpm5.6:latest
    volumes:
      - /data/www:/var/www/html
    networks:
      network:
        ipv4_address: 192.168.101.3

  mongoserv:
    image: mongo:latest
    networks:
      network:
        ipv4_address: 192.168.101.4

networks:
  network:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.101.0/24

